# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Aniket's Website
email: aniketms42@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://friskyspock.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: friskyspock

copyright: 
  year: 2023
  msg: Aniket Masaye # This is a mandatory attribute for copyright to be displayed

preferences:
  search:
    enabled: true
  wiki_style_link: 
    enabled: true
  pagepreview: 
    enabled: true
  backlinks:
    enabled: true

encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap 
  - jekyll-tidy
  - kramdown-mermaid

collections:
    notes:
      output: true
      permalink: /note/:title

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_notes/*.md"
      type: notes
    values:
      layout: "note"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
