#-------------------
# General site settings

social:
- {icon: 'fa-linkedin', link: "https://www.linkedin.com/in/aniket-masaye-90b1851b9/"}
- {icon: 'fa-medium', link: "https://medium.com/@aniketms42"}
- {icon: 'fa-kaggle', link: "https://www.kaggle.com/aniketmasaye"}
- {icon: 'fa-github', link: "https://github.com/friskyspock"}

tags:
  - short: NN
    long: Neural Network
  - short: NLP
    long: Natural Language Processing
  - short: TSF
    long: Time Series Forecasting
  - short: RF
    long: Random Forest
  - short: clustering
    long: Clustering
  - short: MLR
    long: MultiLinear Regression
  