#-------------------
# General site settings

social:
- {icon: 'fa-linkedin', link: "https://www.linkedin.com/in/aniket-masaye/"}
- {icon: 'fa-medium', link: "https://medium.com/@aniketms42"}
- {icon: 'fa-kaggle', link: "https://www.kaggle.com/aniketmasaye"}
- {icon: 'fa-github', link: "https://github.com/friskyspock"}

tags:
  - short: NN
    long: Neural Network
  - short: NLP
    long: Natural Language Processing
  - short: TSF
    long: Time Series Forecasting
  - short: RF
    long: Random Forest
  - short: clustering
    long: Clustering
  - short: MLR
    long: MultiLinear Regression
  - short: CNN
    long: Convolutional Neural Network
  - short: SVM
    long: Support Vector Machine
  - short: NB
    long: Naive Bayes
  - short: Hierarchical
    long: Hierarchical Clustering
  - short: DBScan
    long: DBSCAN
  - short: KMeans
    long: K-Means
  - short: PCA
    long: Principal Component Analysis
  - short: AI
    long: Artificial Intelligence
  - short: Django
    long: Django Web Framework
  